### ISSUE TITLE
How to draw legend on canvas instead of HTML

### ISSUE THREAD

**Issue by roydondsouza** [pa7/heatmap.js#102]
I had a requirement to export heatmap as an image. So I added the following:

In HTML:
< a id="downloadHeatmap" class="btn">Download< / a >

In jQuery:
function downloadCanvas(link, canvasId, filename) {
			    link.href = $('#heatmapArea>canvas')[0].toDataURL();
			    link.download = filename;
			}
				document.getElementById('downloadHeatmap').addEventListener('click', function() {
			    downloadCanvas(this, 'canvas', 'heatmap_floor_name.png');
			}, false);

But after adding legend I realized that legend is not rendered on the canvas. Does this plugin help us make the modification in anyway? https://github.com/flot/flot/pull/42

Or do we have this functionality already?

**Comment by roydondsouza** [comment]
@pa7 does the new version of heatmap.js solve the issue? or do we still need to mention max separately.

**Comment by pa7** [comment]
sorry for the delay

it does not solve this issue because it would make the heatmap generation **very** slow:
- iterate through the whole dataset
- find min & max
- iterate through whole dataset
- render each datapoint

but I still think it would be a great addition to heatmap.js and I'm currently looking into big data processing mechanisms that we could use (and are suitable to use with JavaScript)

**Comment by roydondsouza** [comment]
Thanks. Yes. That will be a good addition; again an option, because sometimes there is a need to set custom max and consider anything above it as max itself :) I have one more feature idea. Will share it as a separate issue.

**Comment by roydondsouza** [comment]
Thanks. Yes. That will be a good addition; again it should not be a default behaviour; just an option, because sometimes there is a need to set custom max [and any points above max are considered as max]
I also have one more feature idea, related to custom zoom (drill down). Will share it as a separate issue.
