### ISSUE TITLE
Leaflet Heatmap becomes mis-aligned after zooming out

### ISSUE THREAD

**Issue by lookuptable** [pa7/heatmap.js#145]
I found that Leaflet Heatmap becomes mis-aligned after zooming out. The problem can be reproduced on the demo page: http://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html . Specifically, after zooming out 4 times. 
![screen shot 2014-10-31 at 5 34 56 pm](https://cloud.githubusercontent.com/assets/5387584/4870229/6020f858-615f-11e4-8055-fdfa63d06d6e.png)

**Comment by hpihkala** [comment]
Is there a workaround for this?

**Comment by sreuland** [comment]
lookuptable has right idea, either the value coming from layerPointToLatLng() is not accounting right or latLngToContainerPoint() does not convert it correctly, I noticed the parent map pane layer had the correct transform coords at all zoom levels, and since heatmap layer was always being transformed into the same top/left point that map pane was at, you could get by with passing the same values through to heatmap transform in _draw() method, it's a hack and hoping a real fix comes in soon, but here it is:

```
_draw: function() {
        if (!this._map) { return; }

        // fix for bug on misalignment of heatmap layer
        var mapPane = this._map.getPanes().mapPane;
        var point = mapPane._leaflet_pos;

        // reposition the layer
        this._el.style[HeatmapOverlay.CSS_TRANSFORM] = 'translate(' +
            -Math.round(point.x) + 'px,' +
            -Math.round(point.y) + 'px)';

        this._update();
    }
```

**Comment by lookuptable** [comment]
Ping.

@pa7 is this issue expected to be fixed?

**Comment by pa7** [comment]
This has been added, I will tag a new version this week which will contain the updated leaflet version
