### ISSUE TITLE
Polylines instead of Points

### ISSUE THREAD

**Issue by alexanderjarvis** [pa7/heatmap.js#150]
I would like to be able to specify polylines as input data instead of points so that I can efficiently generate a heatmap of routes.

Currently I have interpolated points into lines by generating points in-between them but this creates millions of points.

Is it planned to add a line version of heatmap.js? How difficult would it be to add this feature or does it already exist?

(I'm using the leaflet plugin as well).

**Comment by pa7** [comment]
Apologies for the late reply!  That's an interesting use case. Right now it's not really planned but it could be added as a plugin, here is how I'd do it:
- create a plugin w/ store & renderer
- the renderer would have to handle datapoints with x, y, dx, dy
- draw lines with alpha gradient (or if that turns out to be tricky draw the gradients with shadowBlur)
- colorize (just like in the core renderer implementation)

If this is still relevant to you and you'd like to give it a try feel free to reopen the issue
