### ISSUE TITLE
getValueAt only in "hot" zone

### ISSUE THREAD

**Issue by morganzysman** [pa7/heatmap.js#187]
Hello,

I have implemented a heatmap using your lib. First of all great work.
I have a question, i'm using getValueAt to be able to display the heat of a specific spot.
I get the value without a problem, but the further I go in the "blur" zone the lower the heat gets (logical).

I want to keep displaying this blur, but I don't want to display the "Tooltip" when exiting the hottest zone OF EACH point.

Any ideas?

Best regards,

Morgan Zysman

**Comment by pa7** [comment]
Apologies for the late answer.

The current implementation of getValueAt interpolates the values (by reading from the renderer)- that is not optimal and I hope to change that soon. 

In order to solve your problem you could have a whitelist of all your values and and only show the tooltip if the value is part of the whitelist
