### ISSUE TITLE
heatmap.js-master Examples not working

### ISSUE THREAD

**Issue by MahmoudTahaMat** [pa7/heatmap.js#233]
i have downloaded heatmap.js-master and when i extracted the folder and pressed over 

heatmap.js-master\heatmap.js-master\examples\angular-heatmap\index.html 

no heat map previewed  
![image](https://cloud.githubusercontent.com/assets/23422806/20240314/1d15645a-a91e-11e6-9aa9-1a831f404c76.png)

**Comment by pa7** [comment]
There are two potential reasons for that:
1) because you're not serving the files from a web server ( the readme explains how to run the examples locally! )
2) you're having a script blocker (ie adblock+) that's removing heatmap.js

Please reopen if it's still not working after reviewing my feedback
